### ISSUE TITLE
Click on "help" gives an 404-error

### ISSUE THREAD

**Issue by kadauke** [tkadauke/tiny_mon#1]
Hello, my son!

this came, whan I clicked "help":
The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved.

Much greetings from Dad

**Comment by tkadauke** [comment]
Thanks for the report. Added to my TODO-List :-)

**Comment by tkadauke** [comment]
Help exists now for a few pages. The 404 error is gone.
