### ISSUE TITLE
Documentation of using templates

### ISSUE THREAD

**Issue by jbfewo** [tkadauke/tiny_mon#11]
I forked tiny_mon but now I struggle building templates due a lack of documentation. How can I use my variables?

best regrards
jb

**Comment by tkadauke** [comment]
Go to /health_check_templates/new and add the variables that you need. Then set the name and description for the health check. Lastly, create the steps that the health check should have. In the name, description or and of the steps' parameter fields, you can reference variables by enclosing them with two sets of curly braces, like that: {{my_variable}}.

Does that answer your question?

**Comment by jbfewo** [comment]
THX!
the doubled curly braces is what I was looking for.
