### ISSUE TITLE
Migration problem

### ISSUE THREAD

**Issue by ghost** [tkadauke/tiny_mon#2]
Hi,

I tried to install tiny_mon but ran into a problem after executing rake db:migrate:

........
{:migration_name=>"add_deployment_id_to_check_runs"}
==  AddDeploymentIdToCheckRuns: migrating =====================================
-- Executing: CREATE TABLE `new_check_runs` LIKE `check_runs`
rake aborted!
An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: near "LIKE": syntax error: CREATE TABLE `new_check_runs` LIKE `check_runs`

I tried on Ubuntu 10.04 as well as on Mac OSX (Snow Leopard). Any idea what went wrong?

Cheers
Hens

**Comment by tkadauke** [comment]
Hello Hens,

SQLite does not work with the migrations in TinyMon, and it is also not really suited for the kind of concurrency needed by the operations of the monitoring system, at least in production mode. I recommend you try MySQL.

That being said, you could also run rake db:schema:load to set up the database.

Also, you can check out http://tinymon.org for a hosted version of TinyMon.

--Thomas

**Comment by ghost** [comment]
Hi Thomas,

Thanks for the fast answer. To be honest, I am currently more interested to understand your nice software design than using the app. I guess SQLite will do it in that case. Ha! 'db:schema:load' was new to me. Thanks for that.

Have a nice day
Jens

PS: Sigh! It is Jens not Hens -- I was apparently way to tired to write my name correctly.
