### ISSUE TITLE
Registration page changes to German language

### ISSUE THREAD

**Issue by sci-phi** [tkadauke/tiny_mon#3]
When visiting www.TinyMon.org the main page is in English. When clicking on the register link the language switches to German. I have replicated this on 3 different browsers on 2 different machines in unique physical locations/networks.

**Comment by tkadauke** [comment]
That is true. Right now, the current user's preferred language is stored in the database. That means the for guests, nothing is stored and that locale is guessed to be German, which is a bad guess in general. I should put the locale in the URL and have an interface for switching the locale in the header or something.
As a workaround, you can change your language to English if you log in.

**Comment by sci-phi** [comment]
Thanks for your response, but I am leery of filling out a sign-up form without being able to understand the language employed. I'll either have to teach myself German, or wait until I can select my language first.

**Comment by tkadauke** [comment]
http://translate.google.com/translate?sl=auto&tl=en&js=n&prev=_t&hl=en&ie=UTF-8&eotf=1&u=http%3A%2F%2Fmon.tinymon.org%2Fusers%2Fnew&act=url&act=url

**Comment by sci-phi** [comment]
Thanks
