### ISSUE TITLE
Some updates

### ISSUE THREAD

**Issue by janrenz** [tkadauke/tiny_mon#7]
Hi,

i have forked your project and did some updates, so it can run with Postgres, Bootstrap 3, and current Ruby Versiosn.  There are still many deprecation warnings. How do we proceed from here..?
https://github.com/jprberlin/tiny_mon

Do you want to cherry pick the stuff you want for master? Should we finish the update together? I am open for suggestions (i live in Berlin too, so we could also meet up for some coding action)

Jan

**Comment by tkadauke** [comment]
Hi Jan,

Thanks for your interest in tiny_mon :-)

How about you open a pull request so we can discuss your changes in detail?

I'm also open for meeting up, maybe one of these weekends?

--Thomas
